### ISSUE TITLE
HEAVY memory usage on the "updates" updater

### ISSUE THREAD

**Issue by SEAPUNK** [SEAPUNK/channeladvisor-localdb#1]
no idea what's going on, but this will likely help mitigate it

**TODO**
- [ ] Use GetFilteredSkuList instead of GetFilteredInventoryItemList, for performance reasons; compile the list of SKUs, and use them to create a queue for the common update function.
- [x] Once that's done, make a common function to update the data.
- [ ] In the common function, have a debug + benchmark system, that lets you know what size the response is, and how long it took it to process
- [ ] Figure out why the item re-fetching is using up so much memory

**Comment by SEAPUNK** [comment]
4eba21f64c23a08aaf1863a631000fa063d033e6 fixes the memory usage, but adds another item to the TODO list.
